// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMipiw2icElG-cO1Q-WImxt-TnEKEkXeE',
    appId: '1:344458890560:web:a2c1081ac8f0ee0b39fea5',
    messagingSenderId: '344458890560',
    projectId: 'autentication-firebase-2d58d',
    authDomain: 'autentication-firebase-2d58d.firebaseapp.com',
    storageBucket: 'autentication-firebase-2d58d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_QFoezwqRPnElxrCgPXiy7dmbSGPaE4A',
    appId: '1:344458890560:android:187acc9d72fd83de39fea5',
    messagingSenderId: '344458890560',
    projectId: 'autentication-firebase-2d58d',
    storageBucket: 'autentication-firebase-2d58d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwhB7ODDRQGGoWBu3DNJb88RhKQaUrDY',
    appId: '1:344458890560:ios:3cedabc06df30c8a39fea5',
    messagingSenderId: '344458890560',
    projectId: 'autentication-firebase-2d58d',
    storageBucket: 'autentication-firebase-2d58d.appspot.com',
    iosClientId: '344458890560-btec9bsp7pkrn4aporuj6fptm8qev2an.apps.googleusercontent.com',
    iosBundleId: 'com.example.autenticationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjwhB7ODDRQGGoWBu3DNJb88RhKQaUrDY',
    appId: '1:344458890560:ios:3cedabc06df30c8a39fea5',
    messagingSenderId: '344458890560',
    projectId: 'autentication-firebase-2d58d',
    storageBucket: 'autentication-firebase-2d58d.appspot.com',
    iosClientId: '344458890560-btec9bsp7pkrn4aporuj6fptm8qev2an.apps.googleusercontent.com',
    iosBundleId: 'com.example.autenticationFirebase',
  );
}
